-- Pairline Mowing owner dashboard database setup.
-- Replace the email in the policies with the exact Google account email used by the owner.
-- NEVER put a service_role key in the website.

create table if not exists public.site_settings (
  id bigint primary key,
  google_review_url text not null default 'https://www.google.com/search?q=Pairline+Mowing+Port+Huron+MI',
  service_area_text text not null default 'Pairline Mowing serves Port Huron, Michigan and surrounding areas. Contact us to ask whether your address is within our service area.'
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  sort_order integer not null default 1,
  published boolean not null default true
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text not null default '',
  sort_order integer not null default 1,
  published boolean not null default true
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  title text not null default '',
  text text not null,
  sort_order integer not null default 1,
  published boolean not null default true
);

alter table public.site_settings enable row level security;
alter table public.services enable row level security;
alter table public.gallery enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "public read settings" on public.site_settings;
drop policy if exists "owner write settings" on public.site_settings;
drop policy if exists "public read services" on public.services;
drop policy if exists "owner write services" on public.services;
drop policy if exists "public read gallery" on public.gallery;
drop policy if exists "owner write gallery" on public.gallery;
drop policy if exists "public read reviews" on public.reviews;
drop policy if exists "owner write reviews" on public.reviews;

create policy "public read settings" on public.site_settings for select using (true);
create policy "owner write settings" on public.site_settings for all using (lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL')) with check (lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL'));

create policy "public read services" on public.services for select using (published = true);
create policy "owner write services" on public.services for all using (lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL')) with check (lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL'));

create policy "public read gallery" on public.gallery for select using (published = true);
create policy "owner write gallery" on public.gallery for all using (lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL')) with check (lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL'));

create policy "public read reviews" on public.reviews for select using (published = true);
create policy "owner write reviews" on public.reviews for all using (lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL')) with check (lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL'));

insert into public.site_settings (id) values (1) on conflict (id) do nothing;

insert into public.services (name,description,sort_order,published) values
('Lawn Mowing','Consistent mowing to keep your lawn clean, even, and well maintained.',1,true),
('Edging','Crisp edges along sidewalks, driveways, and lawn borders for a finished look.',2,true),
('Weed Whacking','Detailed trimming around areas a mower cannot reach for a cleaner property.',3,true),
('Gutter Cleaning','Help keep gutters clear of leaves and debris so water can flow properly.',4,true),
('Lawn Mower Repairs','Repair help for lawn mowers and related equipment. Contact us with the issue.',5,true),
('Whipper & Equipment Repairs','Repair help for whippers and other lawn equipment. Contact us to discuss your equipment.',6,true)
on conflict do nothing;

insert into public.gallery (image_url,caption,sort_order,published) values
('images/our-work-1.jpeg','Lawn mowing work',1,true),
('images/our-work-2.jpeg','Finished lawn care work',2,true);

insert into public.reviews (name,title,text,sort_order,published) values
('Pamela B.','Great price','I had lawn service yesterday edging my yard and flower beds. Not only did they do an exceptional job but they are very professional and respectful. The owners have great communication and respond quickly to messages. I am so pleased with their professionalism. I have a list of jobs that I am hiring them for, starting with power washing our house this weekend. Then their next project will be deck and porch painting. I am excited and grateful to have them because I have a list of home projects that I need done and my husband and I are not able to accomplish it on our own. It was a blessing to randomly have met them as they were working on a neighbors property. Can’t wait to have my projects finished and I have great confidence that they will do a fantastic job. When the yard work was done, they knocked on the door and asked if I was satisfied with the job. That was so nice and respectful. You can tell they take pride in their work. Exceptional service!!! Highly recommend. 5 stars for sure! Give them a call. You won’t be disappointed!!!',1,true),
('Charly Parker','','These guys did an amazing job! I wanted my grass cut the same day and they were at my house in less than an hour! Not only did they do a beautiful job, they were super respectful. Will absolutely be my go-to lawn service!',2,true),
('Iain Baunoch','Great price','These guys do excellent work. They have a great attention to detail, work quickly and make sure the job is done right.',3,true)
on conflict do nothing;

-- Storage bucket for owner-uploaded project photos.
insert into storage.buckets (id,name,public) values ('site-images','site-images',true) on conflict (id) do update set public = true;

drop policy if exists "public view site images" on storage.objects;
drop policy if exists "owner upload site images" on storage.objects;
drop policy if exists "owner update site images" on storage.objects;
drop policy if exists "owner delete site images" on storage.objects;
create policy "public view site images" on storage.objects for select using (bucket_id = 'site-images');
create policy "owner upload site images" on storage.objects for insert with check (bucket_id = 'site-images' and lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL'));
create policy "owner update site images" on storage.objects for update using (bucket_id = 'site-images' and lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL')) with check (bucket_id = 'site-images' and lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL'));
create policy "owner delete site images" on storage.objects for delete using (bucket_id = 'site-images' and lower(coalesce(auth.jwt()->>'email','')) = lower('REPLACE_WITH_OWNER_GOOGLE_EMAIL'));
